require('telescope').load_extension('fzy_native')
require("telescope").load_extension('pathogen')

vim.keymap.set('n', 'tf', '<cmd>lua require(\'telescope.builtin\').git_files()<cr>', { silent = true })
vim.keymap.set('n', 'tw', ':Telescope pathogen find_files<CR>')
vim.keymap.set('n', 'to', '<cmd>lua require(\'telescope.builtin\').buffers()<cr>')
vim.keymap.set('n', 'ts', ':Telescope pathogen live_grep<CR>', { silent = true })
vim.keymap.set('n', 'th', '<cmd>lua require(\'telescope.builtin\').help_tags()<cr>')
vim.keymap.set('n', 'tl', '<cmd>lua require(\'telescope.builtin\').git_commits()<cr>')
vim.keymap.set('n', 'tr', '<cmd>lua require(\'telescope.builtin\').lsp_references({ fname_width = 100, jump_type = "tab", file_ignore_patterns = { ".*spec.*" } })<cr>')
vim.keymap.set('n', 'tR', '<cmd>lua require(\'telescope.builtin\').lsp_references({ fname_width = 100, jump_type = "tab" })<cr>')
vim.keymap.set('n', 'ty', '<cmd>Cheatsheet<cr>')
